export const SET_GRIDVIEW = 'SET_GRIDVIEW';
export const SET_LISTVIEW = 'SET_LISTVIEW';
export const NAV_MODAL_OPEN = 'NAV_MODAL_OPEN';
export const NAV_MODAL_CLOSE = 'NAV_MODAL_CLOSE';
export const FILTERS_MODAL_OPEN = 'FILTERS_MODAL_OPEN';
export const FILTERS_MODAL_CLOSE = 'FILTERS_MODAL_CLOSE';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';
export const LOAD_BREEDS = 'LOAD_BREEDS';
